Repository OZ-Coding-School/oz_03_main-006-FE, pull requests merged in 2024-07, with the labels that each got.

#7 사이드바 생성 및 UI 디자인(#4)
  config/store.tsx
  config/types.ts
  index.html
  package-lock.json
  package.json
  public/kakao-logo.svg
  public/naver-logo.svg
  src/components/SearchResultItem.tsx
  src/components/common/NavBar.tsx
  src/data/posts.json
  src/index.css
  tailwind.config.js
  tsconfig.app.json
Labels: enhancement

#8 feat: main page background에 naver map 적용
  index.html
  package-lock.json
  package.json
  src/components/common/Layout.tsx
  src/pages/HomePage.tsx
Labels: enhancement

#11 feat: 로그인/회원가입 페이지 생성 및 UI 디자인(#10)
  config/types.ts
  public/google-logo.svg
  src/App.tsx
  src/components/Login.tsx
  src/components/SearchResultItem.tsx
  src/components/SignUp.tsx
  src/components/common/NavBar.tsx
  src/index.css
  src/pages/LoginPage.tsx
Labels: enhancement

#15 community list slide event + marker bounce event
  config/store.tsx
  public/icon/busan.svg
  public/icon/chungbuk.svg
  public/icon/chungnam.svg
  public/icon/daegu.svg
  public/icon/daejeon.svg
  public/icon/gangwon.svg
  public/icon/gwangju.svg
  public/icon/gyeongbuk.svg
  public/icon/gyeonggi.svg
  public/icon/gyeongnam.svg
  public/icon/incheon.svg
  public/icon/jeju.svg
  public/icon/jeonbuk.svg
  public/icon/jeonnam.svg
  public/icon/sejong.svg
  public/icon/seoul.svg
  public/icon/ulsan.svg
  src/components/DropdownList.tsx
  src/data/locationList.ts
  src/pages/HomePage.tsx
Labels: enhancement

#17 포스팅 페이지 기본 ui, 에디터 추가
  package-lock.json
  package.json
  src/pages/PostingPage.css
  src/pages/PostingPage.tsx
Labels: enhancement

#19 community 컴포넌트 및 post 컴포넌트 ui, 라우터 적용
  config/store.tsx
  config/types.ts
  public/empty-heart.svg
  public/full-heart.svg
  src/App.tsx
  src/components/Community.tsx
  src/components/PostCard.tsx
  src/data/community.json
  src/data/weather.json
Labels: enhancement

#18 회원가입/로그인 폼 작성 및 인증 로직 초안 작성(#12, #13)
  config/store.tsx
  config/types.ts
  package-lock.json
  package.json
  src/components/Login.tsx
  src/components/SignUp.tsx
  src/components/common/NavBar.tsx
  src/pages/LoginPage.tsx
Labels: enhancement

#20 인증 절차에 커스텀 alert 창 반영
  config/store.tsx
  config/types.ts
  src/components/Login.tsx
  src/components/SignUp.tsx
  src/components/common/Alert.tsx
Labels: enhancement

#22 feat: infowindow 생성 / navbar여부에 따라서 지도가 밀리는 오류 수정
  config/store.tsx
  public/marker.svg
  src/components/DropdownList.tsx
  src/data/locationList.ts
  src/index.css
  src/pages/HomePage.tsx
Labels: bug, enhancement

#24 feat: carousel 컴포넌트 ui 생성
  package-lock.json
  package.json
  public/images/대구.png
  public/images/부산.png
  public/images/서울.jpg
  src/components/Carousel.css
  src/components/Carousel.tsx
  src/components/Community.tsx
  src/data/icons.json
Labels: enhancement

#27 refactor: 컴포넌트 분리, map이 스크롤 될 때마다 재호출되던 문제 수정, zoom강도 수정
  src/components/Article.tsx
  src/components/Comment.tsx
  src/components/DropdownList.tsx
  src/components/DropdownListContents.tsx
  src/pages/HomePage.tsx
  src/pages/PostDetailPage.tsx
Labels: bug, enhancement, refactoring

#29 포스팅 페이지 ui 추가 및 수정, 유효성 검사 수정
  config/store.tsx
  config/types.ts
  src/components/TagItem.tsx
  src/pages/PostingPage.css
  src/pages/PostingPage.tsx
Labels: enhancement, refactoring

#32 refactor: 포스팅페이지 태그 부분 수정
  src/components/TagItem.tsx
  src/pages/PostingPage.tsx
Labels: refactoring

#34 사이드바 컴포넌트별 분리
  config/store.tsx
  config/types.ts
  src/components/Login.tsx
  src/components/common/NavBar.tsx
  src/components/common/nav/CloseMenuIcon.tsx
  src/components/common/nav/LoginOrUsername.tsx
  src/components/common/nav/LogoAndTitle.tsx
  src/components/common/nav/OpenMenuIcon.tsx
  src/components/common/nav/PostingIcon.tsx
  src/components/common/nav/SearchBar.tsx
  src/components/common/nav/Subtitle.tsx
  src/components/common/nav/UserProfile.tsx
Labels: refactoring

#36 post detail page - comment ui 생성
  src/components/Comment.tsx
  src/data/posts.json
Labels: enhancement

#38 포스팅 디테일 페이지 article ui 작업
  src/components/Article.tsx
Labels: enhancement

#40 feat: post detail page scroll 내부에서 되도록 조정
  src/components/Comment.tsx
  src/pages/PostDetailPage.tsx
Labels: enhancement

#42 My 001 - my page ui 생성
  config/store.tsx
  config/types.ts
  src/components/Community.tsx
  src/components/PostCard.tsx
  src/components/ProfileImage.tsx
  src/pages/MyPage.tsx
Labels: enhancement

#44 feat: seo를 위한 meta tag 와 robots.txt 파일 생성
  index.html
  public/robots.txt
Labels: enhancement

#45 fix: root 스크롤바 없애기
  src/components/Community.tsx
  src/components/Login.tsx
  src/components/SignUp.tsx
  src/components/common/NavBar.tsx
  src/components/common/nav/UserProfile.tsx
  src/index.css
  src/pages/LoginPage.tsx
Labels: bug, duplicate

#47 포스팅 디테일 페이지 - 기능 수정
  src/components/Article.tsx
Labels: bug, refactoring

#50 feat: 댓글 수정 기능 추가+ 스웨거 기준으로 요청 url, body data 변경
  src/components/Comment.tsx
Labels: enhancement

#53 포스팅페이지 - 포스팅 업로드 요청 코드 추가
  src/components/TagItem.tsx
  src/pages/PostingPage.tsx
Labels: enhancement

#54 feat: confirm 알람창 생성
  src/components/common/Alert.tsx
  src/pages/PostingPage.tsx
Labels: enhancement

#56 My Page 프로필 수정
  config/store.tsx
  package-lock.json
  package.json
  src/components/Community.tsx
  src/components/EditModal.tsx
  src/components/PostCard.tsx
  src/components/ProfileImage.tsx
  src/components/ProfileModal.tsx
  src/data/community.json
  src/pages/MyPage.tsx
Labels: enhancement

#59 refactor: api 요청 주소 수정, css 수정
  package-lock.json
  package.json
  src/components/Article.tsx
  src/components/Comment.tsx
  src/components/Community.tsx
  src/components/DropdownList.tsx
  src/components/DropdownListContents.tsx
  src/components/PostCard.tsx
  src/index.css
  src/pages/PostDetailPage.tsx
Labels: bug, refactoring

#60 refactor: 태그 types 수정, api 요청 주소 수정
  config/store.tsx
  config/types.ts
  src/components/TagItem.tsx
  src/pages/PostingPage.tsx
Labels: bug, refactoring

#61 Readme 파일 작성
  README.md
Labels: documentation

#62 로그인 임시 아이디 생성으로 test
  config/types.ts
  package-lock.json
  package.json
  src/App.tsx
  src/api/axios.ts
  src/components/Login.tsx
  src/components/SearchResultItem.tsx
  src/components/SignUp.tsx
  src/components/common/NavBar.tsx
  src/components/common/nav/LoginOrUsername.tsx
  src/components/common/nav/SearchBar.tsx
  src/pages/AuthCallbackPage.tsx
Labels: enhancement

#66 post detail page - api로 변경
  src/components/Comment.tsx
  src/pages/PostDetailPage.tsx
Labels: enhancement

#67 feat: 로딩 컴포넌트 추가
  config/types.ts
  package-lock.json
  package.json
  src/components/Article.tsx
  src/components/common/Loading.tsx
  src/pages/PostDetailPage.tsx
Labels: enhancement, refactoring

#68 refactor: api 주소 수정
  src/pages/PostingPage.tsx
Labels: refactoring

#71 feat: highlight를 api로 수정
  src/api/axios.ts
  src/components/Comment.tsx
  src/components/DropdownList.tsx
  src/components/DropdownListContents.tsx
  src/data/locationList.ts
Labels: enhancement

#77 MyPage ui,로직 수정 및 CommunityPage 로직 수정
  src/components/Community.tsx
  src/components/Login.tsx
  src/components/PostCard.tsx
  src/components/ProfileImage.tsx
  src/data/community.json
  src/data/weather.json
  src/pages/MyPage.tsx
Labels: enhancement

#78 사이드바 검색 및 랭킹 기능 추가(#21, #73)
  config/types.ts
  src/components/Login.tsx
  src/components/SearchResultItem.tsx
  src/components/SignUp.tsx
  src/components/common/Loading.tsx
  src/components/common/NavBar.tsx
  src/components/common/nav/LogoAndTitle.tsx
  src/components/common/nav/Ranking.tsx
  src/components/common/nav/SearchBar.tsx
  src/components/common/nav/Subtitle.tsx
  src/components/common/nav/Tab.tsx
  src/data/posts.json
  src/index.css
  src/pages/LoginPage.tsx
Labels: enhancement

#82 CommunityPage 페이지 네이션 ui 추가
  config/types.ts
  package-lock.json
  package.json
  src/api/axios.ts
  src/components/Carousel.tsx
  src/components/Community.tsx
  src/components/Login.tsx
  src/components/PostCard.tsx
  src/components/pagination.scss
  src/data/community.json
  src/pages/MyPage.tsx
Labels: enhancement

#86 bug: 회원가입/로그인 구현 완료 및 랭킹/검색 버그 수정
  config/types.ts
  src/App.tsx
  src/components/Login.tsx
  src/components/SearchResultItem.tsx
  src/components/SignUp.tsx
  src/components/common/nav/Ranking.tsx
  src/components/common/nav/SearchBar.tsx
  src/components/common/nav/Tab.tsx
Labels: bug, refactoring

#88 MyPage 로그아웃 여부 모달 Ui 추가
  config/store.tsx
  config/types.ts
  src/components/Community.tsx
  src/components/common/Alert.tsx
  src/pages/MyPage.tsx
Labels: enhancement

#89 포스팅 페이지 - 태그, 셀렉트 에러 수정, 마이페이지 ui 수정
  config/types.ts
  src/components/Article.tsx
  src/components/ProfileImage.tsx
  src/components/TagItem.tsx
  src/data/locationList.ts
  src/pages/MyPage.tsx
  src/pages/PostingPage.tsx
  src/utils/postPageHelper.ts
Labels: bug, refactoring

#92 bug: 배포 중 오류 수정
  src/components/PostCard.tsx
  src/components/ProfileImage.tsx
  src/pages/MyPage.tsx
Labels: enhancement

#94 Cp 006
  src/components/common/Alert.tsx
  src/pages/MyPage.tsx
Labels: enhancement

#97 feat: post detail page scroll 위치 수정 / docs: README.md 수정
  README.md
  config/store.tsx
  src/api/axios.ts
  src/components/Article.tsx
  src/components/Comment.tsx
  src/components/common/Alert.tsx
  src/data/community.json
  src/data/posts.json
  src/data/user.json
  src/data/weather.json
  src/pages/PostDetailPage.tsx
  src/pages/PostingPage.tsx
Labels: enhancement

#98 소셜로그인 관련 로직 및 UI 삭제
  src/App.tsx
  src/components/Login.tsx
  src/pages/AuthCallbackPage.tsx
  src/pages/LoginPage.tsx
Labels: wontfix

#100 PostingPage, Article 수정
  config/types.ts
  src/components/Article.tsx
  src/components/Comment.tsx
  src/components/pagination.scss
  src/pages/PostingPage.tsx
Labels: bug, enhancement, refactoring
