Repository OZ-Coding-School/oz_03_main-006-FE, pull requests merged in 2024-08, with the labels that each got.

#103 CP Postcard ui 수정 및 MP ui 추가
  config/types.ts
  src/components/Community.tsx
  src/components/PostCard.css
  src/components/PostCard.tsx
  src/components/ProfileImage.tsx
  src/components/pagination.scss
  src/pages/MyPage.tsx
Labels: enhancement

#104 refactor: 썸네일 로직 수정
  config/types.ts
  src/components/Article.tsx
  src/pages/PostingPage.tsx
Labels: bug

#105 bug: 검색 및 랭킹 본문내용 버그 수정
  src/api/axios.ts
  src/components/Login.tsx
  src/components/SearchResultItem.tsx
  src/components/SignUp.tsx
  src/pages/LoginPage.tsx
Labels: bug

#106 사용자 검색시 사용자가 작성한 게시글이 검색결과에 반영(#21)
  src/components/common/nav/SearchBar.tsx
Labels: duplicate, enhancement

#108 feat: comment white space 추가, outline 제거
  src/components/Comment.tsx
Labels: enhancement

#110 feat: 댓글, 포스트 중복제출 방지 코드 추가 / bug: unCaugth에러 해결 + link 클릭시 confetti 동작 안하도록 수정
  README.md
  src/components/Comment.tsx
  src/components/DropdownList.tsx
  src/components/DropdownListContents.tsx
  src/pages/PostDetailPage.tsx
  src/pages/PostingPage.tsx
Labels: bug, documentation, enhancement

#112 Posting Page - 코드 수정
  src/components/Article.tsx
  src/index.css
  src/pages/PostDetailPage.tsx
  src/pages/PostingPage.tsx
Labels: bug, refactoring

#115 MyPage 프로필 이미지 로직 수정
  src/components/Article.tsx
  src/components/Carousel.tsx
  src/components/Community.tsx
  src/components/PostCard.tsx
  src/components/ProfileImage.tsx
  src/components/ProfileModal.tsx
  src/pages/MyPage.tsx
Labels: enhancement

#116 feat: 비밀번호 변경 기능 추가(#113)
  config/store.tsx
  config/types.ts
  src/App.tsx
  src/components/Login.tsx
  src/components/ResetPassword.tsx
  src/components/SearchResultItem.tsx
  src/components/SignUp.tsx
  src/components/common/Alert.tsx
  src/components/common/nav/LogoAndTitle.tsx
  src/components/common/nav/SearchBar.tsx
  src/components/common/nav/Subtitle.tsx
Labels: enhancement

#117 bug: 앱 실행시 쿠키 확인 여부 삭제
  src/App.tsx
Labels: bug, wontfix

#119 feat: alert 모달 닫힘 기능 추가(#20)
  config/store.tsx
  config/types.ts
  src/components/Article.tsx
  src/components/Comment.tsx
  src/components/ResetPassword.tsx
  src/components/SignUp.tsx
  src/components/common/Alert.tsx
  src/hooks/useCloseAlert.tsx
  src/pages/LoginPage.tsx
  src/pages/MyPage.tsx
  src/pages/PostDetailPage.tsx
  src/pages/PostingPage.tsx
Labels: bug, enhancement

#122 MyPage 프로필 이미지 수정 로직 추가 & get 요청 로직 수정
  src/components/ProfileImage.tsx
  src/components/ProfileModal.tsx
  src/pages/MyPage.tsx
Labels: enhancement

#123 PostingDetailPage - 삭제 시 confrim 모달창 띄우는 것으로 수정
  src/components/Article.tsx
  src/pages/PostingPage.tsx
Labels: refactoring

#125 MyPage 이미지 프로필 수정
  src/pages/MyPage.tsx
Labels: enhancement

#127 My Page - 마이페이지 이미지 프로필 업데이트 로직 수정
  src/pages/MyPage.tsx
Labels: enhancement

#118 Version 1.1
  README.md
  config/store.tsx
  config/types.ts
  src/App.tsx
  src/components/Article.tsx
  src/components/Comment.tsx
  src/components/ProfileImage.tsx
  src/components/ProfileModal.tsx
  src/components/ResetPassword.tsx
  src/components/SignUp.tsx
  src/components/common/Alert.tsx
  src/hooks/useCloseAlert.tsx
  src/pages/LoginPage.tsx
  src/pages/MyPage.tsx
  src/pages/PostDetailPage.tsx
  src/pages/PostingPage.tsx
Labels: bug
